### ISSUE TITLE
Some mild spelling and writing issues

### ISSUE THREAD

**Issue by MOH-Shafizadegan** [MOH-Shafizadegan/Blockchain-Notes#3]
In the 3rd chapter the following modifications are recommended:
- on page 20: future lecture -> future chapter
- on page 20: proposal -> proposer
- on page 24: reference error (Figure 1.4 -> Figure 3.4)
- on page 25: lecture 6 -> chapter 6
- on page 26: use lists (itemize/enumerate)

**Comment by MohammadMow** [comment]
Thank you for your attention to detail :) 
These items have been corrected.
